spring:
  datasource:
    url : "jdbc:h2:mem:patientDB;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1"
    driverClassName: "org.h2.Driver"
    username : sa
    password :
    database-platform=org : database-platform=org
    initialization-mode : embedded
  jpa:
    hibernate :
      naming-strategy : org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      ddl-auto : validate
    show-sql: true
  h2:
    console:
      enabled : true
      path: "/h2"
  data:
    jpa:
      repositories:
        bootstrap-mode: 
        
server:
  port: 9008